/**
 * Export all slices and their actions/selectors
 */

// Cakes
export {
  default as cakesReducer,
  fetchCakes,
  fetchCakeById,
  fetchTopRatedCakes,
  fetchLatestCakes,
  createCake,
  updateCake,
  deleteCake,
  clearError as clearCakesError,
  resetStatus as resetCakesStatus,
  selectAllCakes,
  selectCakeById,
  selectCakeIds,
  selectCakeEntities,
  selectTotalCakes,
  selectCakesStatus,
  selectCakesError,
  selectTopRatedCakes,
  selectLatestCakes,
  selectCakesByTag,
} from './cakesSlice';

// Users
export {
  default as usersReducer,
  fetchUsers,
  fetchUserByUid,
  createUser,
  updateUser,
  deleteUser,
  toggleUserBlock,
  updateUserRole,
  setCurrentUser,
  clearCurrentUser,
  clearError as clearUsersError,
  resetStatus as resetUsersStatus,
  selectAllUsers,
  selectUserByUid,
  selectUserIds,
  selectUserEntities,
  selectTotalUsers,
  selectUsersStatus,
  selectUsersError,
  selectCurrentUser,
  selectAdminUsers,
  selectBlockedUsers,
} from './usersSlice';

// Orders
export {
  default as ordersReducer,
  fetchOrders,
  fetchOrderById,
  fetchOrdersByUser,
  fetchOrdersByStatus,
  createOrder,
  updateOrder,
  updateOrderStatus,
  updatePaymentStatus,
  deleteOrder,
  setStatusFilter,
  clearStatusFilter,
  clearError as clearOrdersError,
  resetStatus as resetOrdersStatus,
  selectAllOrders,
  selectOrderById,
  selectOrderIds,
  selectOrderEntities,
  selectTotalOrders,
  selectOrdersStatus,
  selectOrdersError,
  selectUserOrders,
  selectStatusFilter,
  selectOrdersByStatus,
  selectPendingOrders,
  selectInProcessOrders,
  selectReadyOrders,
  selectDeliveredOrders,
  selectUnpaidOrders,
} from './ordersSlice';

// Feedbacks
export {
  default as feedbacksReducer,
  fetchFeedbacks,
  fetchFeedbackById,
  fetchFeedbacksByCake,
  fetchApprovedFeedbacks,
  fetchFeedbacksByUser,
  createFeedback,
  updateFeedback,
  approveFeedback,
  deleteFeedback,
  clearCakeFeedbacks,
  clearError as clearFeedbacksError,
  resetStatus as resetFeedbacksStatus,
  selectAllFeedbacks,
  selectFeedbackById,
  selectFeedbackIds,
  selectFeedbackEntities,
  selectTotalFeedbacks,
  selectFeedbacksStatus,
  selectFeedbacksError,
  selectPendingApproval,
  selectCakeFeedbacks,
  selectApprovedFeedbacks,
  selectFeedbacksByCakeId,
  selectAverageRating,
} from './feedbacksSlice';
